spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzacloud
    username: postgres
    password: admin
    initialize: true
  data:
    rest:
      base-path: /
  jms:
    template:
      default-destination: pizzacloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: pizzaweb
    password: password
    embedded:
      enabled: false
