spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzacloud
    username: postgres
    password: admin
    initialize: true

---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN