spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzacloud
    username: postgres
    password: admin
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        default_schema: pizzacloud