delete from Ingredient_Ref;
delete from Pizza;
delete from Pizza_Order;

delete from Ingredient;
insert into Ingredient (id, name, type) values ('ThnC', 'Thin Crust', 'CRUST');
insert into Ingredient (id, name, type) values ('ThkC', 'Thick Crust', 'CRUST');
insert into Ingredient (id, name, type) values ('WFC', 'Wood-Fired Crust', 'CRUST');
insert into Ingredient (id, name, type) values ('TS', 'Tomato Sause', 'SAUCE');
insert into Ingredient (id, name, type) values ('WS', 'White Sause', 'SAUCE');
insert into Ingredient (id, name, type) values ('SLM', 'Salami', 'MEAT');
insert into Ingredient (id, name, type) values ('COCK', 'Chicken', 'MEAT');
insert into Ingredient (id, name, type) values ('BCN', 'Bacon', 'MEAT');
insert into Ingredient (id, name, type) values ('ONS', 'Onions', 'VEGGIES');
insert into Ingredient (id, name, type) values ('SWPS', 'Sweet Papers', 'VEGGIES');
insert into Ingredient (id, name, type) values ('PIAP', 'Pinespple', 'VEGGIES');
insert into Ingredient (id, name, type) values ('TMS', 'Tomatoes', 'VEGGIES');
insert into Ingredient (id, name, type) values ('MSRM', 'Mushroom', 'VEGGIES');
insert into Ingredient (id, name, type) values ('MOZA', 'Mozarella', 'CHEESE');
insert into Ingredient (id, name, type) values ('Prov', 'Provolone', 'CHEESE');
insert into Ingredient (id, name, type) values ('GC', 'Goat Cheese', 'CHEESE');
insert into Ingredient (id, name, type) values ('RC', 'Ricotta Cheese', 'CHEESE');
